In [1]:
import pandas as pd
from os import walk
import os
import xlrd
import csv
from tqdm.notebook import tnrange

In [44]:
input_repo = '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리'
output_repo = '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐'

xlsx_output_repo = '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output'
csv_input_repo = output_repo
COLUMNS = ['target', 'input_1', 'input_2', 'input_3']

In [3]:
# 해당 경로의 파일리스트 추출
def get_filelist(input_repo):
    file_list = []
    for (dirpath, dirnames, filenames) in walk(input_repo):
        file_list.extend(filenames)
        break

    return file_list

In [4]:
# 해당 경로의 csv파일의 경로+파일명 리스트 추출
def get_csvlist(input_repo, file_list):
    csv_list = []
    for i in range(len(file_list)):
        filename, file_extension = os.path.splitext(f'{input_repo}/{file_list[i]}')

        if file_extension == '.csv':
            csv_list.append(filename+file_extension)

    return csv_list

In [5]:
# 해당 경로의 csv파일의 경로+파일명 리스트 추출
def get_xlsxlist(input_repo, file_list):
    xlsx_list = []
    for i in range(len(file_list)):
        filename, file_extension = os.path.splitext(f'{input_repo}/{file_list[i]}')

        if file_extension == '.xlsx':
            xlsx_list.append(filename+file_extension)

    return xlsx_list

In [6]:
def concat_csvfile(csv_list):
    COLUMNS = ['target', 'input_1', 'input_2', 'input_3']
    result = pd.concat([pd.read_csv(f) for f in csv_list])    # 라인넘버 기준 안합친파일 합치기
    
    return result

In [7]:
file_list = get_filelist(input_repo)
xlsx_list = get_xlsxlist(input_repo, file_list)

In [8]:
xlsx_list

['/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_김옥주_35.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_김옥주_39.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_남현정_15.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_박상호_17.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_안돈이_21.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_주대희_3.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_김민경_40(100개).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_고은채_22.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_김옥주_18.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_백지은_6(250개).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_이명진_43(110개).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_정다은_28.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_홍선화_9(760개).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_백승진님_42(150개).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_안돈이_32.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_조은빛_26.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_김옥주님_14.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_남현정님_33-1(200개).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_김태이_11(650개).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_정나희_29.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_최하윤님_38-1(200개).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_이한빈님_1.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_전혜진_25.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_문규민_10.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_김이정_24.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_송지혜_23.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_최정미님_2(830개).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_남연희_5(997개).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_황우진_8.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_김지현님_34.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_남현정님_38-2(291개).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_이명진_31.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_임명현_30(100개).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_최하윤_4.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_이한빈님_41-1(200).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_김민경_16.xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_최규하_13(623개).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_이셈님_33-2(84개).xlsx',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/type D 작업물 정리/type_d_data_지승연_20.xlsx']

In [9]:
for i in tnrange(len(xlsx_list)):
    xlsx = pd.read_excel(xlsx_list[i])
    xlsx.to_csv(f'{xlsx_output_repo}/{file_list[i][:-5]}.csv', encoding='utf-8-sig', index=False)

  0%|          | 0/39 [00:00<?, ?it/s]

In [10]:
# D_output 정제
for i in tnrange(len(xlsx_list)):
    with_None_data = pd.read_csv(f'{xlsx_output_repo}/{file_list[i][:-5]}.csv')
    without_None_data = pd.DataFrame(columns=['target', 'input_1', 'input_2', 'input_3'])
    for j in range(len(with_None_data)):
        if with_None_data['길이 확인'][j] != 'FALSE':
            target = with_None_data['띄어쓰기, 맞춤법 체크'][j]
            input_1 = with_None_data['첫번째 구분 구간'][j]
            input_2 = with_None_data['두번째 구분 구간'][j]
            input_3 = with_None_data['세번째 구분 구간'][j]
            without_None_data = without_None_data.append({'target':target, 'input_1':input_1, 'input_2':input_2, 'input_3':input_3}, ignore_index=True)
        else:
            pass
    without_None_data.to_csv(f'/Users/jaytsol/Desktop/Type23 (2)/임시/D_output_2/{file_list[i][:-5]}.csv', encoding='utf-8-sig', index=False)

  0%|          | 0/39 [00:00<?, ?it/s]

In [108]:
# D_output_type5
D_output_type5_input_repo = '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output'
file_list = get_filelist(D_output_type5_input_repo)
csv_list = get_csvlist(D_output_type5_input_repo, file_list)

In [109]:
csv_list

['/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_임명현_30(100개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_김옥주님_14.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_박상호_17.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_정다은_28.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_주대희_3.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_남현정님_38-2(291개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_백지은_6(250개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_김지현님_34.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_최하윤님_38-1(200개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_송지혜_23.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_김민경_16.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_이명진_43(110개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_김옥주_39.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_전혜진_25.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_이한빈님_41-1(200).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_남연희_5(997개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_남현정님_33-1(200개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_남현정_15.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_최정미님_2(830개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_안돈이_21.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_김민경_40(100개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_김옥주_35.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_고은채_22.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_김태이_11(650개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_이셈님_33-2(84개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_김옥주_18.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_이명진_31.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_문규민_10.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_조은빛_26.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_안돈이_32.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_정나희_29.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_백승진님_42(150개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_김이정_24.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_홍선화_9(760개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_황우진_8.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/.DS_.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_이한빈님_1.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_최하윤_4.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/D_output/type_d_data_최규하_13(623개).csv']

In [112]:
# D_output_type5
input_columns = ['첫번째 구분 구간', '두번째 구분 구간', '세번째 구분 구간']
output_columns = ['문장 다듬기', '문장 다듬기.1', '문장 다듬기.2']
for i in tnrange(len(csv_list)):
    with_None_data = pd.read_csv(f'{csv_list[i]}')
    without_None_data = pd.DataFrame(columns=['input', 'output'])
    for j in range(len(with_None_data)):
        for k in range(len(input_columns)):
            if str(with_None_data[input_columns[k]][j]) != 'nan':
                input_data = with_None_data[input_columns[k]][j]
                output_data = with_None_data[output_columns[k]][j]
                without_None_data = without_None_data.append({'input':input_data, 'output':output_data}, ignore_index=True)
            
    without_None_data.to_csv(f'/Users/jaytsol/Desktop/Type23 (2)/임시/Type D 작업물 정리_type5/{csv_list[i][48:]}', encoding='utf-8-sig', index=False)

  0%|          | 0/39 [00:00<?, ?it/s]

In [92]:
listlist = '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료'
listlist_output = '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료_output'
file_list = get_filelist(listlist)
csv_list = get_csvlist(listlist, file_list)

In [14]:
csv_list

['/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료/type_d_data_안돈이님_32.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료/type_d_data_정다은님_28.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료/type_d_data_문규민님_10.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료/type_d_data_지승연님_20.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료/type_d_data_남연희님_5.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료/type_d_data_남현정님_15.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료/type_d_data_백승진님_7.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료/type_d_data_김민경님_16.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료/type_d_data_백승진_7.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료/type_d_data_최하윤님_38-1.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료/type_d_data_박상호님_17.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료/type_d_data_김옥주님_35.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료/type_d_data_김옥주님_18.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료/type_d_data_송지혜님_23.csv']

In [15]:
# 검수완료_정제
for i in tnrange(len(csv_list)):
    with_None_data = pd.read_csv(f'{csv_list[i]}')
    without_None_data = pd.DataFrame(columns=['target', 'input_1', 'input_2', 'input_3'])
    for j in range(len(with_None_data)):
        try:
            if with_None_data['길이 확인'][j] != 'FALSE':
                target = with_None_data['띄어쓰기, 맞춤법 체크'][j]
                input_1 = with_None_data['첫번째 구분 구간'][j]
                input_2 = with_None_data['두번째 구분 구간'][j]
                input_3 = with_None_data['세번째 구분 구간'][j]
                without_None_data = without_None_data.append({'target':target, 'input_1':input_1, 'input_2':input_2, 'input_3':input_3}, ignore_index=True)
            else:
                pass

        except:
            if with_None_data['확인'][j] != 'FALSE':
                target = with_None_data['띄어쓰기, 맞춤법 체크'][j]
                input_1 = with_None_data['첫번째 구분 구간'][j]
                input_2 = with_None_data['두번째 구분 구간'][j]
                input_3 = with_None_data['세번째 구분 구간'][j]
                without_None_data = without_None_data.append({'target':target, 'input_1':input_1, 'input_2':input_2, 'input_3':input_3}, ignore_index=True)
            else:
                pass
            
    without_None_data.to_csv(f'/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료_output/{csv_list[i][45:]}', encoding='utf-8-sig', index=False)

  0%|          | 0/14 [00:00<?, ?it/s]

In [102]:
with_None_data

,lineNumber,원본텍스트,"띄어쓰기, 맞춤법 체크",최소문장 분할,길이 확인,첫번째 구분 구간,문장 다듬기,두번째 구분 구간,문장 다듬기.1,세번째 구분 구간,문장 다듬기.2,첫번째 \r\n문장 길이,두번째 \r\n문장 길이,세번째\r\n 문장 길이,네번째 \r\n문장 길이,Unnamed: 15,Unnamed: 16
0,73234,3) 민사소송에서 소송을 당한 사람은 제1심 공동피고 ***** 주식회사(이하 ‘*...,3) 민사소송에서 소송을 당한 사람은 제1심 공동피고 ***** 주식회사(이하 ‘*...,2개,O,"체결하였는데, 그",체결하였다. 그런데 그,"하고, 구매자가",한다. 그리고 구매자가,NaN,NaN,117,140,157,X,NaN,NaN
1,73236,"민사소송에서 소송을 당한 사람은 다음날인 1.27. 인감증명서 등 문서상으로 권한,...",민사소송에서 소송을 당한 사람은 다음 날인 1.27. 인감증명서 등 문서상으로 권한...,2개,O,하였으나 할부차량에,하였다. 그러나 할부차량에,"하고, 보험회사",했다. 그리고 보험회사,NaN,NaN,196,156,148,X,NaN,NaN
2,73241,마. 민사소송을 일으킨 사람은 이 사건 보험증권을 제출받고 2007. 1.경부터 2...,마. 민사소송을 일으킨 사람은 이 사건 보험 증권을 제출받고 2007. 1. 경부터...,1개,O,"체결하면서, 자동차",체결했다. 그러면서 자동차,NaN,NaN,NaN,NaN,115,X,X,X,NaN,NaN
3,73243,"위 사실관계, 특히 공소외 2가 공소외 3에게 중고자동차 매수 및 대출을 위한 일체...","위 사실관계, 특히 공소 외 2가 공소 외 3에게 중고 자동차 매수 및 대출을 위한...",2개,O,"주었고, 공소",주었다. 그리고 공소,"보면, 공소",본다. 그러면 공소,NaN,NaN,56,167,179,X,NaN,NaN
4,73245,"이 사건 버스에 설정된 근저당권, 특정 재산에 대한 처분 제한 등기 등을 해제하여 ...","이 사건 버스에 설정된 근저당권, 특정 재산에 대한 처분 제한 등기 등을 해제하여 ...",2개,O,"발부되자, ****.**.**피해자에게",발부되었다. 그러자 ****.**.**피해자에게,팔고 그,팔았다. 그리고 그,NaN,NaN,142,126,135,X,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,74330,이는 그대로 방치할 경우 주택 주변에 살포된 휘발유에 충분히 연소될 정도였던 사실을...,이는 그대로 방치할 경우 주택 주변에 살포된 휘발유에 충분히 연소될 정도였던 사실을...,2개,O,거쳐 고의적으로,거쳤다. 그래서 고의적으로,일으킨 점,일으켰다. 그래서,NaN,NaN,171,197,172,X,NaN,NaN
496,74331,"직전의 재판판결과 직전의 재판이 남의 말을 끌어 쓴 제1심판결이 든 증거에 의하면,...",직전의 재판 판결과 직전의 재판이 남의 말을 끌어 쓴 제1심 판결이 든 증거에 의하...,2개,O,복사되어 그,"복사된다, 그래서 그",떠나버렸기 때문에,떠나버렸다. 그렇기 때문에,NaN,NaN,173,169,92,X,NaN,NaN
497,74332,[1] 액화석유가스는 불이 붙고 폭발하기 쉬운 성질을 가지고 있고 그 폭발 사고로 ...,[1] 액화석유가스는 불이 붙고 폭발하기 쉬운 성질을 가지고 있고 그 폭발 사고로 ...,1개,O,있는 경우에,있다. 그러면 그 경우에,NaN,NaN,NaN,NaN,162,X,X,X,NaN,NaN
498,74333,****.**.****시 **분 이 사건 건물의 3층 301호실에 피워놓은 모기향에...,****.**.****시 **분 이 사건 건물의 3층 301호실에 피워놓은 모기향에...,1개,O,"옮겨붙은 다음,","옮겨붙았다. 그리고 그 다음,",NaN,NaN,NaN,NaN,144,X,X,X,NaN,NaN
499,74334,작업 종료 후 이러한 물질을 건물 내부에 방치하여서는 아니됨은 물론 주의나 생각을 ...,작업 종료 후 이러한 물질을 건물 내부에 방치하여서는 아니 됨은 물론 주의나 생각을...,2개,O,"것이고, 용접",것이다. 그리고 용접,"것이므로, 민사소송에서",것이다. 그러므로 민사소송에서,NaN,NaN,128,183,92,X,NaN,NaN

In [106]:
# 검수완료_정제_type5
input_columns = ['첫번째 구분 구간', '두번째 구분 구간', '세번째 구분 구간']
output_columns = ['문장 다듬기', '문장 다듬기.1', '문장 다듬기.2']
for i in tnrange(len(csv_list)):
    with_None_data = pd.read_csv(f'{csv_list[i]}')
    without_None_data = pd.DataFrame(columns=['input', 'output'])
    for j in range(len(with_None_data)):
        for k in range(len(input_columns)):
            if str(with_None_data[input_columns[k]][j]) != 'nan':
                input_data = with_None_data[input_columns[k]][j]
                output_data = with_None_data[output_columns[k]][j]
                without_None_data = without_None_data.append({'input':input_data, 'output':output_data}, ignore_index=True)
            
    without_None_data.to_csv(f'/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료_type5/{csv_list[i][45:]}', encoding='utf-8-sig', index=False)

  0%|          | 0/14 [00:00<?, ?it/s]

In [107]:
without_None_data

             input             output
0        체결하였는데, 그       체결하였다. 그런데 그
1         하고, 구매자가       한다. 그리고 구매자가
2       하였으나 할부차량에     하였다. 그러나 할부차량에
3         하고, 보험회사       했다. 그리고 보험회사
4       체결하면서, 자동차     체결했다. 그러면서 자동차
..             ...                ...
783      떠나버렸기 때문에     떠나버렸다. 그렇기 때문에
784         있는 경우에      있다. 그러면 그 경우에
785       옮겨붙은 다음,   옮겨붙았다. 그리고 그 다음,
786        것이고, 용접        것이다. 그리고 용접
787  것이므로, 민사소송에서   것이다. 그러므로 민사소송에서

[788 rows x 2 columns]

In [26]:
# # 합치고 type5 만들기
# for i in tnrange(len(csv_list)):
#     with_None_data = pd.read_csv(f'{csv_list[i]}')
#     without_None_data = pd.DataFrame(columns=['input', 'output'])
#     for j in range(len(with_None_data)):
#         try:
#             if (with_None_data['길이 확인'][j] != 'FALSE'):
#                 input_data = with_None_data['띄어쓰기, 맞춤법 체크'][j]
#                 output_1 = with_None_data['문장 다듬기'][i]
#                 output_2 = with_None_data['문장 다듬기.1'][i]
#                 output_3 = with_None_data['문장 다듬기.2'][i]
#                 without_None_data = without_None_data.append({'input':input_data, 'output':output_1}, ignore_index=True)
#                 if output_2 != None:
#                     without_None_data = without_None_data.append({'input':input_data, 'output':output_2}, ignore_index=True)
#                     if output_3 != None:
#                         without_None_data = without_None_data.append({'input':input_data, 'output':output_3}, ignore_index=True)
#             else:
#                 pass
#         except:
#             if (with_None_data['확인'][j] != 'FALSE'):
#                 input_data = with_None_data['띄어쓰기, 맞춤법 체크'][j]
#                 output_1 = with_None_data['문장 다듬기'][i]
#                 output_2 = with_None_data['문장 다듬기.1'][i]
#                 output_3 = with_None_data['문장 다듬기.2'][i]
#                 without_None_data = without_None_data.append({'input':input_data, 'output':output_1}, ignore_index=True)
#                 if output_2 != None:
#                     without_None_data = without_None_data.append({'input':input_data, 'output':output_2}, ignore_index=True)
#                     if output_3 != None:
#                         without_None_data = without_None_data.append({'input':input_data, 'output':output_3}, ignore_index=True)
#             else:
#                 pass
# without_None_data.to_csv(f'/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료_output/{csv_list[i][45:]}', encoding='utf-8-sig', index=False)

  0%|          | 0/14 [00:00<?, ?it/s]

In [91]:
csv_without_None_filelist = get_filelist('/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐')
csv_without_None_csvlist = get_csvlist('/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐', csv_without_None_filelist)

In [41]:
concat_result = pd.concat(map(pd.read_csv, csv_without_None_csvlist), ignore_index=True)

In [63]:
concat_result

,target,input_1,input_2,input_3
0,따라서 법률상의 지위인 주주권을 부여하는 유가증권이 발행되지 않은 주식에 관하여 체...,부담하는 반면,NaN,NaN
1,[1] 부동산 매매계약에서 계약금과 잔금 사이에 치르는 돈이 지급되는 등 계약이 본...,처리하여 치워,않고 부동산을,NaN
2,[2] 경제적 이익이 목적인 권리에 관한 매매계약에서 사는 사람이 외국법인인 파는 ...,"몰취된 경우,",NaN,NaN
3,[2] 최초로 무상으로 주는 것으로 간주되는 대상이 되어 세금이 매겨졌거나 세금이 ...,단절되어 서로,NaN,NaN
4,[2] 최초로 무상으로 주는 것으로 간주되는 대상이 되어 세금이 매겨지거나 세금을 ...,적용되어 증여를,NaN,NaN
...,...,...,...,...
31184,NaN,NaN,NaN,NaN
31185,NaN,NaN,NaN,NaN
31186,NaN,NaN,NaN,NaN
31187,NaN,NaN,NaN,NaN
31188,NaN,NaN,NaN,NaN

In [61]:
concat_result_without_None = pd.DataFrame(columns = COLUMNS)
for i in tnrange(len(concat_result)):
    if str(concat_result['input_1'][i]) != 'nan':
        concat_result_without_None = concat_result_without_None.append(concat_result.loc[[i]], ignore_index=True)
    else:
        pass

  0%|          | 0/31189 [00:00<?, ?it/s]

In [62]:
concat_result_without_None

,target,input_1,input_2,input_3
0,따라서 법률상의 지위인 주주권을 부여하는 유가증권이 발행되지 않은 주식에 관하여 체...,부담하는 반면,NaN,NaN
1,[1] 부동산 매매계약에서 계약금과 잔금 사이에 치르는 돈이 지급되는 등 계약이 본...,처리하여 치워,않고 부동산을,NaN
2,[2] 경제적 이익이 목적인 권리에 관한 매매계약에서 사는 사람이 외국법인인 파는 ...,"몰취된 경우,",NaN,NaN
3,[2] 최초로 무상으로 주는 것으로 간주되는 대상이 되어 세금이 매겨졌거나 세금이 ...,단절되어 서로,NaN,NaN
4,[2] 최초로 무상으로 주는 것으로 간주되는 대상이 되어 세금이 매겨지거나 세금을 ...,적용되어 증여를,NaN,NaN
...,...,...,...,...
24421,[2] 컴퓨터 디스켓에 담긴 공적인 문서나 서류가 증거로 사용되는 경우 그 문서 따...,"것이고, 따라서",NaN,NaN
24422,그리고 소유자로부터 물건의 점유권을 빼앗음 된 디지털 저장매체로부터 출력한 공적인 ...,적용되므로 형사소송법,NaN,NaN
24423,구 특허법(****.**.**법률 제6411호로 개정되기 전의 것) 제29조 제1항...,의미이지 그,NaN,NaN
24424,직전의 재판은 형사소송에서 검사에 의해 기소당한 사람> 1이 검사가 형사재판을 신청...,"있고, 위","보아, 형사소송에서",NaN
24425,"기록에 비추어 살펴보면, 직전의 재판의 인정 및 판단은 수긍이 되고, 일이 끝난 후...","없으므로, 거기에",NaN,NaN

In [ ]:
concat_result_without_None

In [64]:
concat_result_without_None.to_csv('/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐2/최종합침_type4.csv', encoding='utf-8-sig', index=False)
# result.to_csv('/Users/jaytsol/Desktop/Type23 (2)/누적/concat/.csv', encoding='utf-8-sig', index=False)

In [66]:
with_None_data

,lineNumber,원본텍스트,"띄어쓰기, 맞춤법 체크",최소문장 분할,길이 확인,첫번째 구분 구간,문장 다듬기,두번째 구분 구간,문장 다듬기.1,세번째 구분 구간,문장 다듬기.2,첫번째 \r\n문장 길이,두번째 \r\n문장 길이,세번째\r\n 문장 길이,네번째 \r\n문장 길이,Unnamed: 15,Unnamed: 16
0,73234,3) 민사소송에서 소송을 당한 사람은 제1심 공동피고 ***** 주식회사(이하 ‘*...,3) 민사소송에서 소송을 당한 사람은 제1심 공동피고 ***** 주식회사(이하 ‘*...,2개,O,"체결하였는데, 그",체결하였다. 그런데 그,"하고, 구매자가",한다. 그리고 구매자가,NaN,NaN,117,140,157,X,NaN,NaN
1,73236,"민사소송에서 소송을 당한 사람은 다음날인 1.27. 인감증명서 등 문서상으로 권한,...",민사소송에서 소송을 당한 사람은 다음 날인 1.27. 인감증명서 등 문서상으로 권한...,2개,O,하였으나 할부차량에,하였다. 그러나 할부차량에,"하고, 보험회사",했다. 그리고 보험회사,NaN,NaN,196,156,148,X,NaN,NaN
2,73241,마. 민사소송을 일으킨 사람은 이 사건 보험증권을 제출받고 2007. 1.경부터 2...,마. 민사소송을 일으킨 사람은 이 사건 보험 증권을 제출받고 2007. 1. 경부터...,1개,O,"체결하면서, 자동차",체결했다. 그러면서 자동차,NaN,NaN,NaN,NaN,115,X,X,X,NaN,NaN
3,73243,"위 사실관계, 특히 공소외 2가 공소외 3에게 중고자동차 매수 및 대출을 위한 일체...","위 사실관계, 특히 공소 외 2가 공소 외 3에게 중고 자동차 매수 및 대출을 위한...",2개,O,"주었고, 공소",주었다. 그리고 공소,"보면, 공소",본다. 그러면 공소,NaN,NaN,56,167,179,X,NaN,NaN
4,73245,"이 사건 버스에 설정된 근저당권, 특정 재산에 대한 처분 제한 등기 등을 해제하여 ...","이 사건 버스에 설정된 근저당권, 특정 재산에 대한 처분 제한 등기 등을 해제하여 ...",2개,O,"발부되자, ****.**.**피해자에게",발부되었다. 그러자 ****.**.**피해자에게,팔고 그,팔았다. 그리고 그,NaN,NaN,142,126,135,X,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,74330,이는 그대로 방치할 경우 주택 주변에 살포된 휘발유에 충분히 연소될 정도였던 사실을...,이는 그대로 방치할 경우 주택 주변에 살포된 휘발유에 충분히 연소될 정도였던 사실을...,2개,O,거쳐 고의적으로,거쳤다. 그래서 고의적으로,일으킨 점,일으켰다. 그래서,NaN,NaN,171,197,172,X,NaN,NaN
496,74331,"직전의 재판판결과 직전의 재판이 남의 말을 끌어 쓴 제1심판결이 든 증거에 의하면,...",직전의 재판 판결과 직전의 재판이 남의 말을 끌어 쓴 제1심 판결이 든 증거에 의하...,2개,O,복사되어 그,"복사된다, 그래서 그",떠나버렸기 때문에,떠나버렸다. 그렇기 때문에,NaN,NaN,173,169,92,X,NaN,NaN
497,74332,[1] 액화석유가스는 불이 붙고 폭발하기 쉬운 성질을 가지고 있고 그 폭발 사고로 ...,[1] 액화석유가스는 불이 붙고 폭발하기 쉬운 성질을 가지고 있고 그 폭발 사고로 ...,1개,O,있는 경우에,있다. 그러면 그 경우에,NaN,NaN,NaN,NaN,162,X,X,X,NaN,NaN
498,74333,****.**.****시 **분 이 사건 건물의 3층 301호실에 피워놓은 모기향에...,****.**.****시 **분 이 사건 건물의 3층 301호실에 피워놓은 모기향에...,1개,O,"옮겨붙은 다음,","옮겨붙았다. 그리고 그 다음,",NaN,NaN,NaN,NaN,144,X,X,X,NaN,NaN
499,74334,작업 종료 후 이러한 물질을 건물 내부에 방치하여서는 아니됨은 물론 주의나 생각을 ...,작업 종료 후 이러한 물질을 건물 내부에 방치하여서는 아니 됨은 물론 주의나 생각을...,2개,O,"것이고, 용접",것이다. 그리고 용접,"것이므로, 민사소송에서",것이다. 그러므로 민사소송에서,NaN,NaN,128,183,92,X,NaN,NaN

In [68]:
type5_input_repo = '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐2'
type5_input_filename = '최종합침_type4.csv'

In [69]:
type5_input = pd.read_csv(f'{type5_input_repo}/{type5_input_filename}')

In [70]:
type5_input

,target,input_1,input_2,input_3
0,따라서 법률상의 지위인 주주권을 부여하는 유가증권이 발행되지 않은 주식에 관하여 체...,부담하는 반면,NaN,NaN
1,[1] 부동산 매매계약에서 계약금과 잔금 사이에 치르는 돈이 지급되는 등 계약이 본...,처리하여 치워,않고 부동산을,NaN
2,[2] 경제적 이익이 목적인 권리에 관한 매매계약에서 사는 사람이 외국법인인 파는 ...,"몰취된 경우,",NaN,NaN
3,[2] 최초로 무상으로 주는 것으로 간주되는 대상이 되어 세금이 매겨졌거나 세금이 ...,단절되어 서로,NaN,NaN
4,[2] 최초로 무상으로 주는 것으로 간주되는 대상이 되어 세금이 매겨지거나 세금을 ...,적용되어 증여를,NaN,NaN
...,...,...,...,...
24421,[2] 컴퓨터 디스켓에 담긴 공적인 문서나 서류가 증거로 사용되는 경우 그 문서 따...,"것이고, 따라서",NaN,NaN
24422,그리고 소유자로부터 물건의 점유권을 빼앗음 된 디지털 저장매체로부터 출력한 공적인 ...,적용되므로 형사소송법,NaN,NaN
24423,구 특허법(****.**.**법률 제6411호로 개정되기 전의 것) 제29조 제1항...,의미이지 그,NaN,NaN
24424,직전의 재판은 형사소송에서 검사에 의해 기소당한 사람> 1이 검사가 형사재판을 신청...,"있고, 위","보아, 형사소송에서",NaN
24425,"기록에 비추어 살펴보면, 직전의 재판의 인정 및 판단은 수긍이 되고, 일이 끝난 후...","없으므로, 거기에",NaN,NaN

In [80]:
type5_output = pd.DataFrame(columns=['input', 'output'])
for i in tnrange(len(type5_input)):
    for j in range(1, 4):
        try:
            if str(type5_input[f'input_{j}'][i]) != 'nan':
                type5_output = type5_output.append({'input':type5_input[f'input_{j}'][i], 'output':None}, ignore_index=True)
        except:
            if str(type5_input[f'input_{j}'][i]) != 'nan':
                type5_output = type5_output.append({'input':type5_input[f'input_{j}'][i], 'output':None}, ignore_index=True)

  0%|          | 0/24426 [00:00<?, ?it/s]

In [81]:
type5_output

             input output
0          부담하는 반면   None
1          처리하여 치워   None
2          않고 부동산을   None
3          몰취된 경우,   None
4          단절되어 서로   None
...            ...    ...
36832  적용되므로 형사소송법   None
36833       의미이지 그   None
36834        있고, 위   None
36835   보아, 형사소송에서   None
36836    없으므로, 거기에   None

[36837 rows x 2 columns]

In [83]:
type5_2_repo = '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐'
file_list = get_filelist(type5_2_repo)
csv_list = get_csvlist(type5_2_repo, file_list)

In [84]:
csv_list

['/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_안돈이님_32.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_임명현_30(100개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김옥주님_14.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_박상호_17.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_정다은_28.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_정다은님_28.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_주대희_3.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_남현정님_38-2(291개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_문규민님_10.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_백지은_6(250개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김지현님_34.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_최하윤님_38-1(200개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_지승연님_20.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_송지혜_23.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_남연희님_5.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김민경_16.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_남현정님_15.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_이명진_43(110개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김옥주_39.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_전혜진_25.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_이한빈님_41-1(200).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_남연희_5(997개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_남현정님_33-1(200개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_백승진님_7.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김민경님_16.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_백승진_7.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_남현정_15.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_최정미님_2(830개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_안돈이_21.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김민경_40(100개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김옥주_35.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_고은채_22.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김태이_11(650개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_최하윤님_38-1.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_이셈님_33-2(84개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김옥주_18.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_이명진_31.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_문규민_10.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_조은빛_26.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_안돈이_32.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_박상호님_17.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_정나희_29.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김옥주님_35.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_백승진님_42(150개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김이정_24.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김옥주님_18.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_홍선화_9(760개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_송지혜님_23.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_황우진_8.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_이한빈님_1.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_최하윤_4.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_최규하_13(623개).csv']

In [86]:
for i in tnrange(len(csv_list)):
    type5_2_tmp = pd.read_csv(csv_list[i])
    type5_2_init = pd.DataFrame(columns=['target', 'input_1', 'input_2', 'input_3', 'output_1', 'output_2', 'output_3'])
    for j in range(len(type5_2_tmp)):
        try:
            if type5_2_tmp['길이 확인'][j] != 'FALSE':
                target = with_None_data['띄어쓰기, 맞춤법 체크'][j]
                input_1 = with_None_data['첫번째 구분 구간'][j]
                input_2 = with_None_data['두번째 구분 구간'][j]
                input_3 = with_None_data['세번째 구분 구간'][j]
                output_1 = with_None_data['문장 다듬기']

  0%|          | 0/52 [00:00<?, ?it/s]

In [89]:
csv_list

['/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_안돈이님_32.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_임명현_30(100개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김옥주님_14.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_박상호_17.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_정다은_28.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_정다은님_28.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_주대희_3.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_남현정님_38-2(291개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_문규민님_10.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_백지은_6(250개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김지현님_34.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_최하윤님_38-1(200개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_지승연님_20.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_송지혜_23.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_남연희님_5.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김민경_16.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_남현정님_15.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_이명진_43(110개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김옥주_39.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_전혜진_25.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_이한빈님_41-1(200).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_남연희_5(997개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_남현정님_33-1(200개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_백승진님_7.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김민경님_16.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_백승진_7.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_남현정_15.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_최정미님_2(830개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_안돈이_21.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김민경_40(100개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김옥주_35.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_고은채_22.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김태이_11(650개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_최하윤님_38-1.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_이셈님_33-2(84개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김옥주_18.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_이명진_31.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_문규민_10.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_조은빛_26.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_안돈이_32.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_박상호님_17.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_정나희_29.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김옥주님_35.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_백승진님_42(150개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김이정_24.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_김옥주님_18.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_홍선화_9(760개).csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_송지혜님_23.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_황우진_8.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_이한빈님_1.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_최하윤_4.csv',
 '/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_최규하_13(623개).csv']

In [15]:
for i in tnrange

  0%|          | 0/14 [00:00<?, ?it/s]

In [88]:
pd.read_csv('/Users/jaytsol/Desktop/Type23 (2)/임시/데이터합쳐/type_d_data_최규하_13(623개).csv')

,target,input_1,input_2,input_3
0,범죄와 형벌에 관한 법률 제243조의 음화등의반포등죄 및 제244조의 음화 등의 제...,"가리키고, 도화의",필요하고 이들의,NaN
1,"피감호청구인의 이전에 죄를 지어 확정된 형벌의 이력 관계, 행적 및 생활태도, 소매...",비추어 피감호청구인의,NaN,NaN
2,사회보호법 제5조 제2항에서 말하는 재범의 위험성은 피감호청구인이 장차 다시 범행을...,의미하므로 그,NaN,NaN
3,"사회보호법 제5조 소정의 재범의 위험성이란 피감호청구인이 그 연령, 가족관계, 직업...","것이고, 그것은",NaN,NaN
4,가. 사회보호법 제5조 제2항에 규정된 재범의 위험성이라 함은 피보호 청구인이 장차...,"의미하고, 그",NaN,NaN
...,...,...,...,...
295,NaN,NaN,NaN,NaN
296,NaN,NaN,NaN,NaN
297,NaN,NaN,NaN,NaN
298,NaN,NaN,NaN,NaN
299,NaN,NaN,NaN,NaN

In [90]:
pd.read_csv(csv_list[1])

,target,input_1,input_2,input_3
0,구 법인세법 시행령 제88조 제1항 제1호에서 정한 높은 가격의 매입으로 보아 부당...,없어 이를,NaN,NaN
1,다. 민사소송을 일으킨 사람이 소장에서 민사소송을 당한 회사의 설립이 모집설립임을 ...,"취하였는바, 이는",조건을 위,NaN
2,[2] 甲이 乙 주식회사의 계약 위반을 이유로 전속계약을 취소하였다고 주장하면서 전...,보냄으로써 甲의,NaN,NaN
3,[2] 재항고인 甲이 피신청인 乙의 법원의 결정과 명령에 불복하여 상소하고취하 전에...,해당하므로 이와,NaN,NaN
4,구 집합건물의 소유 및 관리에 관한 법률 제9조에 의한 정상적인 상태를 충족하지 못...,제출하는 서면을,행사하였거나 지위에서,NaN
...,...,...,...,...
995,NaN,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN
999,NaN,NaN,NaN,NaN

In [15]:
# 검수완료_정제
for i in tnrange(len(csv_list)):
    with_None_data = pd.read_csv(f'{csv_list[i]}')
    without_None_data = pd.DataFrame(columns=['target', 'input_1', 'input_2', 'input_3'])
    for j in range(len(with_None_data)):
        try:
            if with_None_data['길이 확인'][j] != 'FALSE':
                target = with_None_data['띄어쓰기, 맞춤법 체크'][j]
                input_1 = with_None_data['첫번째 구분 구간'][j]
                input_2 = with_None_data['두번째 구분 구간'][j]
                input_3 = with_None_data['세번째 구분 구간'][j]
                without_None_data = without_None_data.append({'target':target, 'input_1':input_1, 'input_2':input_2, 'input_3':input_3}, ignore_index=True)
            else:
                pass

        except:
            if with_None_data['확인'][j] != 'FALSE':
                target = with_None_data['띄어쓰기, 맞춤법 체크'][j]
                input_1 = with_None_data['첫번째 구분 구간'][j]
                input_2 = with_None_data['두번째 구분 구간'][j]
                input_3 = with_None_data['세번째 구분 구간'][j]
                without_None_data = without_None_data.append({'target':target, 'input_1':input_1, 'input_2':input_2, 'input_3':input_3}, ignore_index=True)
            else:
                pass
            
    without_None_data.to_csv(f'/Users/jaytsol/Desktop/Type23 (2)/임시/검수_완료_output/{csv_list[i][45:]}', encoding='utf-8-sig', index=False)

  0%|          | 0/14 [00:00<?, ?it/s]